# Generated by Django 3.2.4 on 2021-06-11 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='text_editor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('text', models.CharField(max_length=3000)),
                ('det', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
